/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  imprese: [{type: 'autogenerated', dirName: 'imprese'}],  // foldername
  informatica: [{type: 'autogenerated', dirName: 'informatica'}],  // foldername
  localita: [{type: 'autogenerated', dirName: 'localita'}],  // foldername
  lavoro: [{type: 'autogenerated', dirName: 'lavoro'}],  // foldername

};

module.exports = sidebars;