/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {

  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  prima: [{type: 'autogenerated', dirName: 'imprese'}],  // foldername
  seconda: [{type: 'autogenerated', dirName: 'docs-informatica'}],  // foldername

};

module.exports = sidebars;